//AUTH TYPES
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

//ERROR TYPES
export const GET_ERROR = 'GET_ERRORS'
export const CLEAR_ERROR = 'CLEAR_ERRORS'

//BOARD TYPES
export const GET_BOARD = 'GET_BOARD'
export const GET_ALL_BOARDS = 'GET_ALL_BOARDS'
export const DELETE_BOARD = 'DELETE_BOARD'
export const BOARD_LOADING = 'BOARD_LOADING'
export const BOARD_LOADED = 'BOARD_LOADED'

//NOTE TYPES
export const ADD_NOTE = 'ADD_NOTE'
export const DEL_NOTE = 'DEL_NOTE'
export const SAVE_NOTE = 'SAVE_NOTE'